

*************************
*************************

Begin log for program initialized on 
****NEW EXCEPTION THROWN****
Program critical error at Tue Jun 30 02:58:05 2015

Traceback (most recent call last):
  File "bigred.py", line 194, in <module>
    #login to reddit with your u/n and password
  File "bigred.py", line 170, in __main__
    asdf #random exception
NameError: global name 'ClientException' is not defined
****END OF EXCEPTION****
